#!/bin/sh
cp -r python-adafruit_gpio ..
cp -r python-adafruit-pureio ..
cp -r python-ads1x15 ..
cp -r python-awesome-slugify ..
cp -r python-colored ..
cp -r python-cython ..
cp -r python-libpulseaudio ..
cp -r python-MechanicalSoup ..
cp -r python-mpd ..
cp -r python-mpd2 ..
cp -r python-nose ..
cp -r python-oauth2client ..
cp -r python-pid ..
cp -r python-pidfile ..
cp -r python-pulsectl ..
cp -r python-pycryptodome ..
cp -r python-pylast ..
cp -r python-pytest-runner ..
cp -r python-regex ..
cp -r python-rplcd ..
cp -r python-rsa ..
cp -r python-tendo ..
cp -r python-unidecode ..
cp -r udisks-glue ..
