#!/bin/sh

# APPLICATION
NAME="Headunit"
DAEMON="/mnt/PIHU_APP/defender-headunit/hu.py"

if [ -n "$HU_SOURCE" ]; then
  DAEMONOPTS="--source $HU_SOURCE"
else
  DAEMONOPTS=""
fi

[ -x $DAEMON ] || exit 1

retval=0

# PID (created by application)
PIDFILE=/var/run/hu.pid

start() {
        echo "Starting $NAME..."
        start-stop-daemon -x $DAEMON -p $PIDFILE -S -- $DAEMONOPTS
        retval=$?
        #  echo "Starting $NAME..."
        #  $DAEMON $DAEMONOPTS &
}

stop() {
        echo "Stopping $NAME"
        start-stop-daemon -x $DAEMON -p $PIDFILE -K
        retval=$?
        #if [ -f $PIDFILE ]; then
        #    echo "Stopping $NAME"
        #    PID=`cat $PIDFILE`
        #    kill -HUP $PID
        #    rm -f $PIDFILE
        #else
        #    echo "$PIDFILE not found, aborting..."
        #fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $retval

